---@type string, AGFNamespace
local addonName, ns = ...

-- QuestieDB owns the quest catalogue. Bundled geometry still places maps and transport hubs;
-- it never limits which quests exist. Questie supplies live availability policy (including events).

local ADDON = "QuestieDB"
-- The contract this file was written against. QuestieDB checks a RANGE (its minSupportedContract..contractVersion),
-- so a newer additive QuestieDB keeps working and new quests appear automatically via GetAllIds; only a rising
-- minSupportedContract (or a removed field, caught below) makes the catalogue unavailable, and the reason is shown.
local CONTRACT = 2
-- Generated by tools/catalogue_revision.py from the catalogue producers and bundled geometry.
local CACHE_REVISION = "a6b3bce23cbe7b3a0897ff5d07928281d7c8b8824ca43e6eb4b834acb170bb89"
-- A build is sliced across frames: at a millisecond a frame the tracker stayed empty for most of a minute, and a few
-- frames a second for a few seconds is the smaller cost. A matching saved catalogue is adopted whole at login, so
-- only a first login or a changed key builds.
local SLICE_MS = 2
-- Questie can load and then never report ready, when its own startup stops on an error for one character. Waiting
-- longer than this would leave the guide on its loading line for the whole session, so the catalogue is read without
-- Questie's live policy instead. A ready callback that arrives later reads it again.
local READY_WAIT = 60
-- Daily and weekly quest flags also identify repeatable work.
local REPEATABLE_FLAGS = 4096 + 32768

local QUEST_FIELDS = {
	"name",
	"questLevel",
	"requiredLevel",
	"requiredMaxLevel",
	"requiredRaces",
	"requiredClasses",
	"zoneOrSort",
	"startedBy",
	"finishedBy",
	"preQuestGroup",
	"preQuestSingle",
	"requiredSkill",
	"requiredMinRep",
	"requiredMaxRep",
	"exclusiveTo",
	"nextQuestInChain",
	"breadcrumbForQuestId",
	"questFlags",
	"specialFlags",
	"objectives",
	"triggerEnd",
}
ns.QuestieFields = {
	spawns = { "spawns" },
	drops = { "npcDrops", "objectDrops", "itemDrops" },
}
local GIVER_FIELDS = { "name", ns.QuestieFields.spawns[1], "zoneID" }
-- What says whether an NPC keeps an inn and which side it serves.
local SERVICE_FIELDS = { "npcFlags", "friendlyToFaction" }
-- QuestieDB's Classic NPC flags for an innkeeper and a trainer, and its letters for the sides an NPC is friendly to.
local INNKEEPER, TRAINER, SIDES = 128, 16, { A = 1, H = 2, AH = 3 }
local NPC_FIELDS = { GIVER_FIELDS[1], GIVER_FIELDS[2], GIVER_FIELDS[3], SERVICE_FIELDS[1], SERVICE_FIELDS[2] }
local ENTITIES = {
	{ name = "Quest", keys = "questKeys", fields = QUEST_FIELDS },
	{ name = "Npc", keys = "npcKeys", fields = NPC_FIELDS },
	{ name = "Object", keys = "objectKeys", fields = GIVER_FIELDS },
	{ name = "Item", keys = "itemKeys", fields = ns.QuestieFields.drops },
}

---@type AGFQuestieStatus
local status = { state = "unavailable", settled = false }
ns.QuestieStatus = status

-- One of ZoneDB's tables, which QuestieDB keeps as Lua source: run with no globals, since it is only a table literal.
---@param source any
---@return table?
local function Table(source)
	local chunk = type(source) == "string" and loadstring(source)
	if not chunk then
		return nil
	end
	setfenv(chunk, {})
	local ok, value = pcall(chunk)
	return ok and type(value) == "table" and value or nil
end

---@param lib AGFQuestieDB
---@param entities {name: string, keys: string, fields: string[]}[]
---@param extraFields? table<string, string[]>
---@return string?
local function MissingField(lib, entities, extraFields)
	for _, entity in ipairs(entities) do
		local meta = lib.Meta and lib.Meta[entity.name .. "Meta"]
		local keys, reader = meta and meta[entity.keys], lib[entity.name]
		if type(keys) ~= "table" or type(reader) ~= "table" or type(reader.GetAll) ~= "function" then
			return entity.name
		end
		if extraFields and type(reader.GetAllIds) ~= "function" then
			return entity.name .. ".GetAllIds"
		end
		---@type string[]
		local fields = extraFields and extraFields[entity.name] or entity.fields
		for _, field in ipairs(fields) do
			if not keys[field] then
				return field
			end
		end
	end
end

-- QuestieDB as this file reads it, or nil and why not (an ns.L line).
---@return AGFQuestieDB?, string?, AGFQuestieZones?
local function Fit()
	local lib = LibQuestieDB
	if type(lib) ~= "table" then
		return nil, ns.L.QUESTIE_ABSENT
	end
	-- Keep QuestieDB's own mismatch message (it names both versions) rather than the generic line, so the audit shows
	-- exactly why the catalogue is unavailable.
	local called, fits, why = pcall(lib.RequireContract, CONTRACT)
	if not (called and fits) then
		return nil, why or ns.L.QUESTIE_CONTRACT
	end
	if C_AddOns.GetAddOnMetadata(ADDON, "X-Flavor") ~= "Forever" then
		return nil, ns.L.QUESTIE_FLAVOUR
	end
	local missing = MissingField(lib, ENTITIES)
	if missing then
		return nil, ns.L.QUESTIE_FIELD:format(missing)
	end
	if type(lib.Quest.GetAllIds) ~= "function" then
		return nil, ns.L.QUESTIE_FIELD:format("Quest.GetAllIds")
	end
	local zoneDB = type(lib.Support) == "table" and lib.Support.Get("ZoneDB") or {}
	local private = zoneDB["private"]
	if type(private) ~= "table" then
		return nil, ns.L.QUESTIE_ZONES
	end
	local area, parent, instances =
		Table(private.areaIdToUiMapId), Table(private.subZoneToParentZone), zoneDB.instanceIdToAreaId
	if not (area and parent and type(instances) == "table") then
		return nil, ns.L.QUESTIE_ZONES
	end
	return lib,
		nil,
		{
			area = area,
			areaOverride = Table(private.areaIdToUiMapIdOverride) or {},
			parent = parent,
			parentOverride = Table(private.subZoneToParentZoneOverride) or {},
			instances = instances,
		}
end

-- The single class a bitmask names, or nil when it names none or several.
---@param classes integer
---@return integer?
local function SingleClass(classes)
	local found
	for class = 1, 11 do
		if bit.band(classes, 2 ^ (class - 1)) ~= 0 then
			if found then
				return nil
			end
			found = class
		end
	end
	return found
end

-- QuestieDB's race masks: the old races keep their bits (77 the Alliance's, 178 the Horde's), and Forever's
-- Skyborne are bits 32 (Alliance) and 33 (Horde), past what the client's 32-bit `bit` library holds.
local ALLIANCE, HORDE = 77 + 2 ^ 32, 178 + 2 ^ 33

---@param mask integer
---@param set integer
---@return boolean shares whether the two masks have a bit in common
local function Shares(mask, set)
	for index = 0, 33 do
		local bit = 2 ^ index
		if math.floor(mask / bit) % 2 == 1 and math.floor(set / bit) % 2 == 1 then
			return true
		end
	end
	return false
end

---@param races integer
---@return integer 1 Alliance, 2 Horde, 3 both, 0 neither (tools/gen_quests.py faction)
local function Side(races)
	if races == 0 then
		return 3
	end
	return (Shares(races, ALLIANCE) and 1 or 0) + (Shares(races, HORDE) and 2 or 0)
end

-- A mask that names every old race of the sides it reaches is a side's quest, not a race's: `side` says so, and
-- the Skyborne of that side take it though the mask predates them.
---@param races integer
---@return integer?
local function Races(races)
	local old = (Shares(races, 77) and 77 or 0) + (Shares(races, 178) and 178 or 0)
	for index = 0, 7 do
		local bit = 2 ^ index
		if math.floor(old / bit) % 2 == 1 and math.floor(races / bit) % 2 == 0 then
			return races
		end
	end
	return nil
end

---@param value number
---@return number
local function Round(value)
	return math.floor(value * 1e4 + 0.5) / 1e4
end

-- Whether sort key `a` comes before `b`.
---@param a any[]
---@param b any[]
---@return boolean
local function Before(a, b)
	for i = 1, #a do
		if a[i] ~= b[i] then
			return a[i] < b[i]
		end
	end
	return false
end

-- The instance each area belongs to, among the instances `keep` accepts: an instance's own area, then the alias areas
-- ZoneDB lists for its dungeon. Also ZoneDB's dungeon rows by area.
---@param lib AGFQuestieDB
---@param zones AGFQuestieZones
---@param keep fun(instance: integer): boolean
---@return table<integer, integer> instanceOf, table<integer, table> dungeons
local function InstanceAreas(lib, zones, keep)
	local zoneDB = lib.Support.Get("ZoneDB")
	local dungeons = zoneDB and zoneDB.private and zoneDB.private.dungeons or {}
	local instanceOf = {}
	for instance, area in pairs(zones.instances) do
		if keep(instance) then
			instanceOf[area] = instance
		end
	end
	for instance, area in pairs(zones.instances) do
		local dungeon = keep(instance) and dungeons[area]
		for _, alias in ipairs(type(dungeon) == "table" and type(dungeon[2]) == "table" and dungeon[2] or {}) do
			instanceOf[alias] = instanceOf[alias] or instance
		end
	end
	return instanceOf, dungeons
end

-- Whether `instance` (a Map.ID) is a dungeon the data lists, not a raid.
---@param instance integer
---@return boolean
local function Dungeon(instance)
	return ns.Data.instances[instance] ~= nil and not ns.Data.instances[instance].raid
end

-- Where each dungeon's way in is, from QuestieDB's zone support. Read once and in one go (a few dozen rows), so the
-- first draw of a dungeon and every later one name the same point.
---@type table<integer, AGFPoint>?
local entrances

---@param instance integer a Map.ID
---@return AGFPoint?
function ns.DungeonEntrance(instance)
	if not entrances then
		local lib, _, zones = Fit()
		if not lib or not zones then
			return nil
		end
		local found = {}
		local _, dungeons = InstanceAreas(lib, zones, Dungeon)
		for id, area in pairs(zones.instances) do
			local dungeon = Dungeon(id) and dungeons[area]
			-- Forever's support points are already converted; applying EraToForever again would move them.
			for _, spot in ipairs(type(dungeon) == "table" and type(dungeon[4]) == "table" and dungeon[4] or {}) do
				local map = zones.areaOverride[spot[1]] or zones.area[spot[1]]
				local x, y = spot[2], spot[3]
				if map and ns.Data.maps[map] and type(x) == "number" and type(y) == "number" then
					local point = { map = map, x = x / 100, y = y / 100 }
					if ns.Model.ValidPlace(point) and not found[id] then
						found[id] = point
					end
				end
			end
		end
		entrances = found
	end
	return entrances[instance]
end

-- The build, as a coroutine body: ns.Data's replacement, or an error.
---@param lib AGFQuestieDB
---@param zones AGFQuestieZones
---@param bundled AGFData
---@param yield fun()
---@return table data an AGFData
local function Build(lib, zones, bundled, yield)
	local function Parent(area)
		return zones.parentOverride[area] or zones.parent[area]
	end
	-- An area's map, or its parent zone's; only a map the data places.
	local function Map(area)
		local map = zones.areaOverride[area] or zones.area[area]
		local parent = not map and Parent(area)
		map = map or (parent and (zones.areaOverride[parent] or zones.area[parent]))
		return type(map) == "number" and bundled.maps[map] and map or nil
	end
	local instanceOf = InstanceAreas(lib, zones, function(instance)
		return bundled.instances[instance] ~= nil
	end)
	-- Every quest start and finish, for the towns they stand in (QuestieTowns.lua).
	local places = {}
	-- Each quest's mutually exclusive links, resolved into one group id after every quest is read.
	local exclusive = {}
	-- Each giver's name, its spawns on maps the data places (0-100 on its area's map), and its usual map.
	local givers = { Npc = {}, Object = {} }
	---@type AGFQuestieReads
	local reads = { Npc = {}, Object = {}, Item = {} }
	-- One Npc row per build: the place fields a giver needs, the service fields the innkeeper and trainer passes
	-- need, and the spawns the objective pass reads. nil means not read yet, false means no row for the id.
	---@type table<integer, AGFQuestieNpcRow|false>
	local npcRows = {}
	-- A row's spawns on maps the data places (0-100 on its area's map), in the data's order.
	---@param spawns table<integer, number[][]>
	---@return AGFPoint[]
	local function Spots(spawns)
		local spots = {}
		for area, coordinates in pairs(spawns) do
			local map = type(area) == "number" and Map(area)
			for _, xy in ipairs(map and coordinates or {}) do
				local x, y = tonumber(xy[1]), tonumber(xy[2])
				if x and y and x >= 0 and x <= 100 and y >= 0 and y <= 100 then
					table.insert(spots, { map = map, x = Round(x / 100), y = Round(y / 100) })
				end
			end
		end
		return spots
	end
	---@param id integer
	---@return AGFQuestieNpcRow|false
	local function NpcRow(id)
		local row = npcRows[id]
		if row == nil then
			local values = lib.Npc.GetAll(id, NPC_FIELDS)
			local spawns = values and values[2]
			row = false
			if values and type(values[1]) == "string" and type(spawns) == "table" then
				local flags = tonumber(values[4]) or 0
				row = {
					name = values[1],
					spots = Spots(spawns),
					home = type(values[3]) == "number" and Map(values[3]) or nil,
					inn = bit.band(flags, INNKEEPER) ~= 0,
					trains = bit.band(flags, TRAINER) ~= 0,
					side = SIDES[values[5]],
				}
			end
			npcRows[id] = row
			reads.Npc[id] = spawns or false
		end
		return row
	end
	---@param kind "Npc"|"Object"
	---@param id integer
	---@return {name: string, spots: {map: integer, x: number, y: number}[], home: integer?}|false
	local function Giver(kind, id)
		local giver = givers[kind][id]
		if giver == nil then
			local row
			if kind == "Npc" then
				row = NpcRow(id)
			else
				local values = lib.Object.GetAll(id, GIVER_FIELDS)
				if values and type(values[1]) == "string" and type(values[2]) == "table" then
					row = {
						name = values[1],
						spots = Spots(values[2]),
						home = type(values[3]) == "number" and Map(values[3]) or nil,
					}
				end
				-- The objective pass reads the same spawns; hand it this answer instead of asking again.
				reads.Object[id] = values and row and values[2] or false
			end
			giver = row and { name = row.name, spots = row.spots, home = row.home } or false
			givers[kind][id] = giver
		end
		return giver
	end
	-- Where a quest starts or ends among its givers' spawns: in its zone first, then on the giver's usual map, then
	-- the lowest map, name and point. An item giver or unknown spawn has no pickup waypoint.
	local function Place(by, zone)
		local best, bestKey
		for index, kind in ipairs({ "Npc", "Object" }) do
			for _, id in ipairs(type(by) == "table" and type(by[index]) == "table" and by[index] or {}) do
				local giver = Giver(kind, id)
				if giver then
					for _, spot in ipairs(giver.spots) do
						local home = spot.map == giver.home and 0 or 1
						local key = { spot.map == zone and 0 or 1, home, spot.map, giver.name, spot.x, spot.y }
						if not bestKey or Before(key, bestKey) then
							bestKey = key
							best = { map = spot.map, x = spot.x, y = spot.y, name = giver.name }
							best.npc = kind == "Npc" and id or nil
						end
					end
				end
			end
		end
		places[#places + 1] = best
		return best
	end
	-- Whether QuestieDB's flags call an NPC a trainer. The bundled roles miss Forever's extra class and race
	-- combinations, so a class quest's giver needs this bit before its class is stamped on it.
	local function Trains(id)
		local row = NpcRow(id)
		return row and row.trains or false
	end

	local ids, quests = lib.Quest.GetAllIds(), {}
	status.catalogueCount, status.questCount = #ids, 0
	local xpSource = lib.Support.Get("QuestXP")
	local xp = xpSource and xpSource.db or {}
	for _, id in ipairs(ids) do
		local values = lib.Quest.GetAll(id, QUEST_FIELDS)
		if values then
			local v = {}
			for index, field in ipairs(QUEST_FIELDS) do
				v[field] = values[index]
			end
			local races, classes = tonumber(v.requiredRaces or 0), tonumber(v.requiredClasses or 0)
			local level, minimum = tonumber(v.questLevel), tonumber(v.requiredLevel)
			if type(v.name) == "string" and races and classes and level and minimum then
				local quest = {
					title = v.name,
					level = level,
					min = minimum,
					max = tonumber(v.requiredMaxLevel),
					side = Side(races),
					races = races ~= 0 and Races(races) or nil,
					classes = classes ~= 0 and classes or nil,
					provider = true,
				}
				local area = tonumber(v.zoneOrSort) or 0
				local zone = area > 0 and Map(area) or nil
				quest.start, quest.finish = Place(v.startedBy, zone), Place(v.finishedBy, zone)
				quest.zone = zone or (quest.start or quest.finish or {}).map
				local instance = area > 0 and (instanceOf[area] or instanceOf[Parent(area) or false])
				if instance and bundled.instances[instance] then
					quest.dungeon, quest.raid = instance, bundled.instances[instance].raid
				end
				local flags, special = tonumber(v.questFlags) or 0, tonumber(v.specialFlags) or 0
				local tag = C_QuestLog.GetQuestTagInfo and C_QuestLog.GetQuestTagInfo(id)
				quest.elite = tag and tag.tagID == 1 or nil
				quest.raid = quest.raid or bit.band(flags, 64) ~= 0 or nil
				quest.repeatable = (bit.band(special, 1) ~= 0 or bit.band(flags, REPEATABLE_FLAGS) ~= 0) or nil
				quest.xp = type(xp[id]) == "table" and tonumber(xp[id][2]) or nil
				quest.flags = bit.band(special, 2) ~= 0 and { event = true } or nil
				local following = tonumber(v.nextQuestInChain) or 0
				quest.next = following > 0 and following or nil
				local breadcrumb = tonumber(v.breadcrumbForQuestId) or 0
				quest.breadcrumb = breadcrumb > 0 and breadcrumb or nil
				-- Preserve relationships for chain displays. Live Questie policy evaluates their full semantics.
				local group, single = v.preQuestGroup, v.preQuestSingle
				quest.pre = type(group) == "table" and group or nil
				quest.preAny = type(single) == "table" and single or nil
				-- QuestieDB puts a lone prerequisite in preQuestSingle, where it is the one quest required: the same as a
				-- one-element preQuestGroup, so the model can prove the chain's total. With both fields present the group is
				-- the all-of set and the single is the any-of set, and the model reads each as such.
				if not quest.pre and quest.preAny and #quest.preAny == 1 then
					quest.pre, quest.preAny = quest.preAny, nil
				end
				local skill = v.requiredSkill
				local skillID = type(skill) == "table" and tonumber(skill[1]) or nil
				local skillValue = type(skill) == "table" and tonumber(skill[2]) or nil
				if skillID and skillValue and skillValue > 0 then
					quest.skill = { id = skillID, value = skillValue }
				end
				local low, high = v.requiredMinRep, v.requiredMaxRep
				local lowFaction = type(low) == "table" and tonumber(low[1]) or nil
				local highFaction = type(high) == "table" and tonumber(high[1]) or nil
				if lowFaction and highFaction and lowFaction ~= highFaction then
					-- AGFQuest holds one faction's standing: with a minimum and a maximum for different factions the data
					-- cannot establish eligibility, so the quest gets no pickup.
					quest.start = nil
				elseif lowFaction or highFaction then
					local rep = { faction = lowFaction or highFaction }
					if lowFaction then
						rep.min = tonumber(low[2])
					end
					if highFaction then
						rep.max = tonumber(high[2])
					end
					quest.rep = rep
				end
				if type(v.exclusiveTo) == "table" then
					exclusive[id] = v.exclusiveTo
				end
				local start = quest.start
				if start and quest.classes and start.npc then
					-- A class quest's giver is its class's trainer. The bundled role names the class it trains; without one,
					-- QuestieDB's trainer flag plus the quest's single required class name it, so a plain quest giver is
					-- never called a trainer.
					local role = bundled.roles[start.npc]
					local trained = role and role.class
					if not trained and Trains(start.npc) then
						trained = SingleClass(quest.classes)
					end
					start.trainer = trained
				end
				if not quest.dungeon then
					quest.need, quest.obj, quest.kinds, quest.objectivesUnknown = ns.QuestieObjectives(
						lib,
						v.objectives,
						v.triggerEnd,
						quest.zone,
						bundled,
						Map,
						yield,
						id,
						reads
					)
				end
				quests[id] = quest
				status.questCount = status.questCount + 1
			end
		end
		yield()
	end
	-- Yield unconditionally so the exclusive-group pass and NPC loop start with a fresh slice budget.
	coroutine.yield()
	-- QuestieDB names mutually exclusive quests directly; AGFQuest carries one id per exclusive group. Each
	-- connected component of those links becomes a group id, its lowest quest, so every member closes the others'
	-- siblings. A quest linked only to a quest the data does not hold stands alone.
	local members = {}
	local function Root(id)
		local root = id
		while members[root] ~= root do
			root = members[root]
		end
		while members[id] ~= root do
			members[id], id = root, members[id]
		end
		return root
	end
	for id, exclusiveTo in pairs(exclusive) do
		members[id] = members[id] or id
		for _, other in ipairs(exclusiveTo) do
			if quests[other] then
				members[other] = members[other] or other
			end
		end
	end
	for id, exclusiveTo in pairs(exclusive) do
		for _, other in ipairs(exclusiveTo) do
			if members[other] then
				local root, member = Root(id), Root(other)
				if root ~= member then
					members[math.max(root, member)] = math.min(root, member)
				end
			end
		end
	end
	local sizes = {}
	for id in pairs(members) do
		local root = Root(id)
		sizes[root] = (sizes[root] or 0) + 1
	end
	for id in pairs(members) do
		local root = Root(id)
		if sizes[root] > 1 then
			quests[id].group = root
		end
	end
	local hubs = ns.QuestieTowns.Build(bundled, places, yield)
	-- Who trains, keeps an inn or runs a battleground queue, where and for which side. What a trainer teaches is the
	-- bundled `roles`; an innkeeper is QuestieDB's flag. An NPC with no side or no spawn on a placed map is left out.
	local npcs = {}
	for _, id in ipairs(type(lib.Npc.GetAllIds) == "function" and lib.Npc.GetAllIds() or {}) do
		local role = bundled.roles[id]
		local row = npcRows[id]
		if row == nil then
			-- An NPC with a bundled role always needs its place; any other is read for its service flags alone, and an
			-- innkeeper then read again for its place. An NPC already read as a quest giver keeps that row.
			if role then
				row = NpcRow(id)
			else
				local values = lib.Npc.GetAll(id, SERVICE_FIELDS)
				local inn = values and bit.band(tonumber(values[1]) or 0, INNKEEPER) ~= 0
				local side = values and SIDES[values[2]]
				row = side and inn and NpcRow(id) or false
				npcRows[id] = row
				reads.Npc[id] = reads.Npc[id] or false
			end
		end
		local inn, side = row and row.inn or false, row and row.side
		local giver = side and (role or inn) and Giver("Npc", id)
		if giver then
			local best, bestKey
			for _, spot in ipairs(giver.spots) do
				local key = { spot.map == giver.home and 0 or 1, spot.map, spot.x, spot.y }
				if not bestKey or Before(key, bestKey) then
					best, bestKey = spot, key
				end
			end
			if best then
				local npc = { inn = inn or nil, side = side }
				for key, value in pairs(role or {}) do
					npc[key] = value
				end
				npc.place = { map = best.map, x = best.x, y = best.y, name = giver.name }
				npc.place.hub = ns.QuestieTowns.Hub(bundled, npc.place)
				npcs[id] = npc
			end
		end
		yield()
	end
	-- A service NPC in a town no quest place reaches still needs the town named.
	for _, npc in pairs(npcs) do
		local hub = npc.place.hub
		if hub and not hubs[hub] then
			hubs[hub] = { name = ns.QuestieTowns.Name(bundled, npc.place) }
		end
	end
	local data = { quests = quests, hubs = hubs, npcs = npcs }
	for key, value in pairs(bundled) do
		data[key] = data[key] or value
	end
	return data
end

-- Runs the build a slice a frame from login, then swaps ns.Data and rebuilds the route.
local bundled = ns.Data
local empty = {}
for key, value in pairs(bundled) do
	empty[key] = value
end
empty.quests, empty.hubs = {}, {}
ns.Data = empty --[[@as AGFData]]

-- The inputs the composed catalogue depends on. QuestieDB corrects its quest, NPC and object rows from the
-- character's class and faction (UnitClassBase, UnitFactionGroup) and names them in the client's language
-- (GetLocale), and the client's build and this addon's version decide the record shape, so a catalogue built under
-- one set of inputs is never used under another. Development installs use the producer fingerprint too, so an
-- unchanged reload adopts its catalogue while a source change rebuilds it.
---@param version string QuestieDB's version
---@return string?
local function CatalogueKey(version)
	local mine = C_AddOns.GetAddOnMetadata(addonName, "Version")
	if type(mine) ~= "string" or mine == "" then
		return nil
	end
	if mine:sub(1, 1) == "@" then
		mine = "development"
	end
	local _, build = GetBuildInfo()
	return table.concat({
		"version=" .. mine,
		"catalogue=" .. CACHE_REVISION,
		"questiedb=" .. version,
		"flavour=" .. tostring(C_AddOns.GetAddOnMetadata(ADDON, "X-Flavor")),
		"client=" .. tostring(build),
		"locale=" .. tostring(GetLocale()),
		"class=" .. tostring(UnitClassBase("player")),
		"faction=" .. tostring(UnitFactionGroup("player")),
	}, "\n")
end

-- The catalogue the saved data carries for this character, or nil. Per character, because QuestieDB's class and
-- faction corrections make one character's rows another's. Only a table is considered; anything else rebuilds.
---@return table?
local function Saved()
	local charDB = AdventureGuideForeverCharDB
	local saved = type(charDB) == "table" and charDB.catalogue or nil
	return type(saved) == "table" and saved or nil
end

-- Whether a saved catalogue is the shape this version writes. A truncated or foreign save fails and is rebuilt;
-- the check reads one quest, so it cannot stall a frame, and it never errors.
---@param saved table
---@return boolean
local function Shape(saved)
	if type(saved.quests) ~= "table" or type(saved.hubs) ~= "table" or type(saved.npcs) ~= "table" then
		return false
	end
	local id, quest = next(saved.quests)
	return id ~= nil and type(quest) == "table" and type(quest.title) == "string" and type(quest.level) == "number"
end

-- The saved catalogue as ns.Data: the bundled geometry with the saved quests, towns and service NPCs over it, the
-- same overlay Build ends with.
---@param saved table
---@return table data an AGFData
local function Assemble(saved)
	local data = {}
	for key, value in pairs(bundled) do
		data[key] = value
	end
	data.quests, data.hubs, data.npcs = saved.quests, saved.hubs, saved.npcs
	return data
end

-- Keeps this login's catalogue for the next one, under the key that produced it.
---@param result AGFData
---@param key string
local function Remember(result, key)
	if type(AdventureGuideForeverCharDB) == "table" then
		AdventureGuideForeverCharDB.catalogue = {
			key = key,
			quests = result.quests,
			hubs = result.hubs,
			npcs = result.npcs,
		}
	end
end

-- The saved catalogue for this character under `key`, or nil: the key names the exact inputs that produced it, and
-- the shape check rejects a truncated or foreign save.
---@param key string
---@return table?
local function Matching(key)
	local saved = Saved()
	return saved and saved.key == key and Shape(saved) and saved or nil
end

-- The saved catalogue, adopted from the saved variables and addon metadata alone, so it is available at login
-- without waiting for Questie. Questie's live availability is policy, not record data, so it joins later; the ready
-- callback rebuilds the route once for it. True when the catalogue is now ns.Data.
---@param version string QuestieDB's version
---@return boolean adopted
local function Adopt(version)
	local key = CatalogueKey(version)
	local saved = key and Matching(key)
	if not saved then
		return false
	end
	status.state, status.version, status.settled = "questie", version, true
	ns.Data = Assemble(saved) --[[@as AGFData]]
	return true
end

local function Start()
	local version = C_AddOns.GetAddOnMetadata(ADDON, "Version") or "?"
	if Adopt(version) then
		-- The catalogue is already in place; this rebuild brings the live policy in.
		ns.Invalidate()
		return
	end
	local lib, reason, zones = Fit()
	if not lib or not zones then
		status.state, status.reason, status.settled = "unavailable", reason, true
		ns.Invalidate()
		return
	end
	local key = CatalogueKey(version)
	local started = 0
	local co = coroutine.create(Build)
	local function Yield()
		if debugprofilestop() - started >= SLICE_MS then
			coroutine.yield()
		end
	end
	status.state = "building"
	local function Step()
		started = debugprofilestop()
		local ok, result = coroutine.resume(co, lib, zones, bundled, Yield)
		if not ok then
			status.state, status.reason, status.settled =
				"unavailable", ns.L.QUESTIE_FAILED:format(tostring(result)), true
			ns.Invalidate()
		elseif coroutine.status(co) ~= "dead" then
			C_Timer.After(0, Step)
		else
			status.state, status.version, status.settled = "questie", version, true
			if key then
				Remember(result, key)
			end
			ns.Data = result --[[@as AGFData]]
			ns.Invalidate()
		end
	end
	C_Timer.After(0, Step)
end

EventUtil.ContinueAfterAllEvents(function()
	-- The earliest safe point: the saved variables have loaded, and the class and faction the key depends on are
	-- readable. Adoption here means the route is planned from the saved records at login, and Questie's ready
	-- callback only joins its live policy.
	local version = C_AddOns.GetAddOnMetadata(ADDON, "Version") or "?"
	local adopted = Adopt(version)
	if adopted then
		ns.Invalidate()
	else
		status.state = "building"
	end
	if Questie and Questie.API and Questie.API.RegisterOnReady then
		local ready = false
		Questie.API.RegisterOnReady(function()
			ready = true
			if adopted then
				-- The saved catalogue stands; one rebuild brings Questie's live policy in.
				ns.Invalidate()
			else
				Start()
			end
		end)
		C_Timer.After(READY_WAIT, function()
			if not ready and not adopted then
				Start()
			end
		end)
		if Questie.API.RegisterForQuestUpdates then
			Questie.API.RegisterForQuestUpdates(function(questId)
				-- An update that leaves the quest's availability where the last plan found it cannot move the route.
				if type(questId) == "number" and not ns.State.QuestUpdateChanged(questId) then
					return
				end
				ns.State.QuestChanged()
			end)
		end
	elseif not adopted then
		Start()
	end
end, "PLAYER_LOGIN")

function ns.SourceHint()
	if status.state == "building" then
		return ns.L.AUDIT_QUESTIE_BUILDING
	end
	if status.state ~= "questie" then
		return ns.L.QUESTIE_ENABLE
	end
	if not (Questie and Questie.API and Questie.API.isReady) then
		return ns.L.QUESTIE_POLICY
	end
end
