-- Generated by tools/diff_forever.py — do not edit.
-- wago.tools DB2 at 1.60.1.69913 (Forever) against 1.15.9.69722 (Classic Era): an ID only Forever has, Forever added.
-- quests: zone map -> the added QuestV2 IDs whose QuestPOIBlob sits on it. A quest with no blob has no zone,
-- so it is left out; the addon compares these with Data.quests at runtime.
-- areas: the added AreaTable IDs.
---@type string, AGFNamespace
local _, ns = ...
-- stylua: ignore
ns.Data.forever = {
	quests = {
		[1429] = { 92750, 92751 },
		[1436] = { 92742, 92744, 92745, 92747, 92748, 92752, 92753, 92819 },
		[1446] = { 96912, 96913, 96914, 96915, 96916, 96917, 96918, 96919, 96920, 96921 },
		[1453] = { 92748, 92749, 92750, 92751, 92752 },
		[2482] = { 91564 },
	},
	areas = {
		[16144] = true, [16234] = true, [16508] = true, [16509] = true, [16510] = true, [16511] = true,
		[16512] = true, [16513] = true, [16514] = true, [16515] = true, [16516] = true, [16517] = true,
		[16518] = true, [16519] = true, [16520] = true, [16521] = true, [16522] = true, [16523] = true,
		[16524] = true, [16532] = true, [16537] = true, [16544] = true, [16558] = true, [16559] = true,
		[16560] = true, [16562] = true, [16577] = true, [16591] = true, [16593] = true, [16602] = true,
		[16603] = true, [16604] = true, [16605] = true, [16606] = true, [16607] = true, [16608] = true,
		[16609] = true, [16610] = true, [16611] = true, [16612] = true, [16614] = true, [16615] = true,
		[16616] = true, [16617] = true, [16622] = true, [16623] = true, [16624] = true, [16625] = true,
		[16626] = true, [16628] = true, [16629] = true, [16630] = true, [16631] = true, [16632] = true,
		[16635] = true, [16636] = true, [16637] = true, [16638] = true, [16650] = true, [16651] = true,
		[16653] = true, [16654] = true, [16655] = true, [16656] = true, [16657] = true, [16658] = true,
		[16659] = true, [16660] = true, [16661] = true, [16662] = true, [16663] = true, [16672] = true,
		[16673] = true, [16674] = true, [16675] = true, [16676] = true, [16677] = true, [16678] = true,
		[16679] = true, [16685] = true, [16720] = true, [16723] = true, [16724] = true, [16725] = true,
		[16726] = true, [16727] = true, [16728] = true, [16729] = true, [16731] = true, [16732] = true,
		[16734] = true, [16735] = true, [16736] = true, [16737] = true, [16739] = true, [16740] = true,
		[16741] = true, [16742] = true, [16743] = true, [16744] = true, [16756] = true, [16757] = true,
		[16758] = true, [16759] = true, [16760] = true, [16761] = true, [16762] = true, [16763] = true,
		[16764] = true, [16765] = true, [16772] = true, [16820] = true, [16833] = true, [16848] = true,
		[16849] = true, [16853] = true, [16866] = true, [16867] = true, [16868] = true, [16870] = true,
		[16876] = true, [16877] = true, [16878] = true, [16879] = true, [16880] = true, [16881] = true,
		[16916] = true, [16919] = true, [16941] = true, [16985] = true, [16986] = true, [16988] = true,
		[17044] = true, [17045] = true, [17050] = true, [17052] = true, [17065] = true, [17066] = true,
		[17144] = true, [17145] = true, [17191] = true, [17203] = true, [17221] = true, [17223] = true,
		[17674] = true, [17675] = true, [17676] = true, [17677] = true, [17678] = true, [17684] = true,
		[17707] = true, [17716] = true, [17732] = true, [17738] = true, [17780] = true, [17803] = true,
		[17804] = true, [17808] = true, [17809] = true, [17824] = true,
	},
}
