-- Writes the test-only quest corpus (tests/fixtures/quests.lua and tests/fixtures/towns.lua) from a pinned
-- QuestieDB release, composed by the addon's own QuestieSource build so the fixture is what a player's game
-- carries. Run by tools/gen_corpus.py, which downloads and verifies the release first; never shipped.
--
-- AGF_QUESTIEDB: the release's addon directory (holding QuestieDB_Forever.toc)
-- AGF_CORPUS_NAMES: a Lua file returning { skills = {[id] = name}, factions = {[id] = name} }, for the gate names
-- AGF_QUESTIEDB_TAG, AGF_QUESTIEDB_SHA256, AGF_CLIENT_BUILD: the pins the headers name
local root = assert(os.getenv("AGF_QUESTIEDB"), "AGF_QUESTIEDB is not set")
local namesPath = assert(os.getenv("AGF_CORPUS_NAMES"), "AGF_CORPUS_NAMES is not set")
local tag = os.getenv("AGF_QUESTIEDB_TAG") or "?"
local sha = os.getenv("AGF_QUESTIEDB_SHA256") or "?"
local build = os.getenv("AGF_CLIENT_BUILD") or "?"
local source = "https://github.com/Questie/QuestieDB/releases/tag/" .. tag

local lib = assert(loadfile("tools/questiedb_load.lua"))()(root, "QuestieDB_Forever.toc")
local harness = dofile("tests/harness.lua")
local h = harness.load({
	questiedb = {},
	-- The corpus keeps only what QuestieDB carries, never the test client facts.
	clientFacts = false,
	setup = function(loaded)
		loaded.G.LibQuestieDB = lib
		loaded.metadata.QuestieDB = { Version = tag, ["X-Flavor"] = "Forever" }
	end,
})
if h.ns.QuestieStatus.state ~= "questie" then
	error("QuestieDB corpus build failed: " .. tostring(h.ns.QuestieStatus.reason))
end
local data = h.ns.Data
local names = assert(loadfile(namesPath))()

-- The model fixture decides eligibility itself, so the live-policy marker QuestieSource sets in game is dropped.
for _, quest in pairs(data.quests) do
	quest.provider = nil
end

-- One Lua literal per value: a dense 1..n table positionally, any other table by sorted key (numbers first), so
-- the same release gives byte-identical files and a sparse slot map keeps its keys.
local function Lua(value)
	local kind = type(value)
	if kind == "string" then
		return ("%q"):format(value):gsub("\\\n", "\\n")
	elseif kind == "boolean" then
		return tostring(value)
	elseif kind ~= "table" then
		return tostring(value)
	end
	local keys = {}
	for key in pairs(value) do
		keys[#keys + 1] = key
	end
	table.sort(keys, function(a, b)
		if type(a) ~= type(b) then
			return type(a) == "number"
		end
		return a < b
	end)
	local dense = #keys > 0
	for index, key in ipairs(keys) do
		if type(key) ~= "number" or key ~= index then
			dense = false
			break
		end
	end
	local parts = {}
	if dense then
		for _, key in ipairs(keys) do
			parts[#parts + 1] = Lua(value[key])
		end
	else
		for _, key in ipairs(keys) do
			local name = type(key) == "number" and ("[%d]"):format(key)
				or (key:match("^[%a_][%w_]*$") and key or ("[%q]"):format(key))
			parts[#parts + 1] = name .. " = " .. Lua(value[key])
		end
	end
	return "{ " .. table.concat(parts, ", ") .. " }"
end

local function Rows(rows)
	local ids, out = {}, {}
	for id in pairs(rows) do
		ids[#ids + 1] = id
	end
	table.sort(ids)
	for _, id in ipairs(ids) do
		out[#out + 1] = ("\t\t[%d] = %s,"):format(id, Lua(rows[id]))
	end
	return table.concat(out, "\n"), #ids
end

local function Write(path, lines)
	local file = assert(io.open(path, "w"))
	file:write(table.concat(lines, "\n"), "\n")
	file:close()
end

local quests, questCount = Rows(data.quests)

-- Only the skill lines and factions a corpus quest gates on, by the client's own names.
local skills, factions = {}, {}
for _, quest in pairs(data.quests) do
	if quest.skill then
		skills[quest.skill.id] = { name = names.skills[quest.skill.id] }
	end
	if quest.rep then
		factions[quest.rep.faction] = { name = names.factions[quest.rep.faction] }
	end
end
for id, entry in pairs(skills) do
	if not entry.name then
		error("no client name for skill line " .. id)
	end
end
for id, entry in pairs(factions) do
	if not entry.name then
		error("no client name for faction " .. id)
	end
end

Write("tests/fixtures/quests.lua", {
	"-- Generated by tools/gen_corpus.py: do not edit.",
	"-- QuestieDB Forever, pinned: " .. source .. " (sha256 " .. sha .. ")",
	"-- Test-only quest corpus: the model fixture and the test harness's QuestieDB mirror source.",
	"-- NOT shipped in the addon; in game, quest records come from the installed QuestieDB (QuestieSource.lua).",
	"-- Composed by the addon's own QuestieSource build over the release's baked store, for one fixed character:",
	"-- QuestieDB corrects startedBy and nextQuestInChain by race, class and faction, so the build pins an",
	"-- Alliance warrior. The live-policy marker `provider` is dropped, so the model's own gates decide.",
	"-- Facts only the client supplies at runtime (objective counts, the timed flag and the elite tag) are not",
	"-- here: a spec names the quests it needs them for in tests/fixtures/client.lua.",
	"-- skill, rep: RequiredSkill/Values and RequiredMin/MaxRep; group: the quests exclusiveTo names, as one id;",
	"-- breadcrumb: BreadcrumbForQuestId, open only while the quest it leads to is neither done nor in the log.",
	"-- need: each objective's slot; 0 until the client's log gives its count. obj: where one is done, as",
	"-- { slot, x, y, r[, map] }, x and y in thousandths of the map. xp: the XP a start gives.",
	"-- flags: event, a script completes it; dungeon, raid and repeatable follow the data. pre and preAny are",
	"-- preQuestGroup and preQuestSingle; next is NextQuestInChain; a class quest's giver carries `trainer`.",
	"-- stylua: ignore",
	"local quests = {",
	quests,
	"}",
	"",
	"return quests",
})

local hubs, hubCount = Rows(data.hubs)
local npcs, npcCount = Rows(data.npcs)
local skillRows, skillCount = Rows(skills)
local factionRows, factionCount = Rows(factions)
Write("tests/fixtures/towns.lua", {
	"-- Generated by tools/gen_corpus.py: do not edit.",
	"-- QuestieDB Forever, pinned: " .. source .. " (sha256 " .. sha .. ")",
	"-- Test-only towns for the quest corpus beside it (quests.lua): each hub's name, each role NPC's side and place,",
	"-- and the English names of the skills and factions a corpus quest gates on (wago.tools client build " .. build,
	"-- SkillLine and Faction). NOT shipped in the addon; in game the QuestieDB build composes hubs and NPC places",
	"-- (QuestieTowns.lua, QuestieSource.lua).",
	"-- stylua: ignore",
	"return {",
	"\thubs = {",
	hubs,
	"\t},",
	"\tnpcs = {",
	npcs,
	"\t},",
	"\tskills = {",
	skillRows,
	"\t},",
	"\tfactions = {",
	factionRows,
	"\t},",
	"}",
})

print(
	("corpus: %d quests, %d hubs, %d npcs, %d skills, %d factions"):format(
		questCount,
		hubCount,
		npcCount,
		skillCount,
		factionCount
	)
)
