#!/usr/bin/env python3
"""Diff Forever's DB2 tables against Classic Era's and emit what Forever added (stdlib only).

Both builds come from wago.tools, cached in tools/.cache like gen_quests.py's sources. An ID Forever's table has
and Era's lacks is one Forever added: no hand-kept list, no ID threshold. Data/Forever.lua carries the slice the
addon reads (docs/design.md §2.1, honest coverage); the other tables are only printed, for the roadmap's later work.
"""

import argparse
import csv
import sys
import urllib.error
from collections import defaultdict

from gen_quests import BUILD, ROOT, db2

ERA = "1.15.9.69722"
OUTPUT = ROOT / "Data" / "Forever.lua"
# Printed only: the IDs that later work (new lands, flight masters) starts from.
REPORTED = ("TaxiNodes", "Map")
AREAS_PER_LINE = 6


def added(forever, era):
    """The IDs Forever's rows have and Era's lack, in order."""
    return sorted({int(r["ID"]) for r in forever} - {int(r["ID"]) for r in era})


def zone_quests(blobs, quests):
    """Each zone map -> the Forever-added quests whose QuestPOIBlob sits on it; a quest with no blob has no zone."""
    wanted, zones = set(quests), defaultdict(set)
    for row in blobs:
        quest, ui_map = int(row["QuestID"]), int(row["UiMapID"])
        if quest in wanted and ui_map > 0:
            zones[ui_map].add(quest)
    return {ui_map: sorted(ids) for ui_map, ids in sorted(zones.items())}


def render(zones, areas):
    lines = [
        "-- Generated by tools/diff_forever.py — do not edit.",
        f"-- wago.tools DB2 at {BUILD} (Forever) against {ERA} (Classic Era): an ID only Forever has, Forever added.",
        "-- quests: zone map -> the added QuestV2 IDs whose QuestPOIBlob sits on it. A quest with no blob has no zone,",
        "-- so it is left out; the addon compares these with Data.quests at runtime.",
        "-- areas: the added AreaTable IDs.",
        "---@type string, AGFNamespace",
        "local _, ns = ...",
        "-- stylua: ignore",
        "ns.Data.forever = {",
        "\tquests = {",
    ]
    lines.extend(f"\t\t[{ui_map}] = {{ {', '.join(map(str, ids))} }}," for ui_map, ids in zones.items())
    lines.extend(["\t},", "\tareas = {"])
    for start in range(0, len(areas), AREAS_PER_LINE):
        lines.append("\t\t" + " ".join(f"[{area}] = true," for area in areas[start : start + AREAS_PER_LINE]))
    return "\n".join(lines + ["\t},", "}", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--refresh", action="store_true", help="redownload the pinned sources")
    mode.add_argument("--offline", action="store_true", help="require cached sources")
    options = vars(parser.parse_args())

    def both(name, columns=("ID",)):
        return added(db2(name, columns, **options), db2(name, columns, build=ERA, **options))

    quests = both("QuestV2")
    zones = zone_quests(db2("QuestPOIBlob", ("QuestID", "UiMapID"), **options), quests)
    areas = both("AreaTable")
    if not quests or not areas:
        raise ValueError("Forever added nothing; leaving existing output untouched")
    print(f"QuestV2: {len(quests)} added, {sum(map(len, zones.values()))} placed on {len(zones)} zone maps")
    print(f"AreaTable: {len(areas)} added")
    for name in REPORTED:
        ids = both(name)
        print(f"{name}: {len(ids)} added: {', '.join(map(str, ids))}")
    OUTPUT.write_text(render(zones, areas), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({OUTPUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, KeyError, csv.Error, urllib.error.URLError) as error:
        sys.exit(f"diff_forever: {error}")
