#!/usr/bin/env python3
"""Diff Forever's DB2 tables against Classic Era's and emit what Forever added (stdlib only).

Both builds come from wago.tools, cached in tools/.cache like gen_quests.py's sources. An ID Forever's table has
and Era's lacks is one Forever added: no hand-kept list, no ID threshold. Data/Forever.lua carries the slice the
addon reads (docs/design.md §2.1, honest coverage); the other tables are only printed, for the roadmap's later work.
"""

import argparse
import csv
import sys
import urllib.error
from collections import defaultdict

from gen_quests import BUILD, ROOT, db2, flight_masters, lua, project

ERA = "1.15.9.69722"
OUTPUT = ROOT / "Data" / "Forever.lua"
# Printed only: the IDs that later work starts from.
REPORTED = ("TaxiNodes", "Map")
AREAS_PER_LINE = 6
# What `flight_masters` reads.
TAXI_COLUMNS = ("ID", "Name_lang", "ContinentID", "Pos_0", "Pos_1", "Flags", "ConditionID", "VisibilityConditionID")
TAXI_COLUMNS += ("MountCreatureID_0", "MountCreatureID_1")


def added(forever, era):
    """The IDs Forever's rows have and Era's lack, in order."""
    return sorted({int(r["ID"]) for r in forever} - {int(r["ID"]) for r in era})


def zone_quests(blobs, quests):
    """Each zone map -> the Forever-added quests whose QuestPOIBlob sits on it; a quest with no blob has no zone."""
    wanted, zones = set(quests), defaultdict(set)
    for row in blobs:
        quest, ui_map = int(row["QuestID"]), int(row["UiMapID"])
        if quest in wanted and ui_map > 0:
            zones[ui_map].add(quest)
    return {ui_map: sorted(ids) for ui_map, ids in sorted(zones.items())}


def lands(maps, assignments, area_rows, taxi_nodes, added_nodes):
    """Each zone map (UiMap Type 3) in `maps`, the ones Forever added: its name, the level range of its areas and the
    flight masters it has (roadmap #14).

    The range is the least and greatest non-zero AreaTable.ExplorationLevel among the map's areas (its
    UiMapAssignment AreaIDs) and their children; a land whose areas all have 0 (Mount Hyjal, Shen'dralas) has no range
    and is left out. `taxi` holds each flight master (`flight_masters`) Forever added (`added_nodes`) that serves a
    side (TaxiNodes Flags 1 Alliance, 2 Horde) and stands on the map, projected as a quest giver is, by node ID: the
    map's rectangle overhangs its neighbours' older flight masters (Lakeshire, Kargath).
    """
    zones = {int(r["ID"]): r["Name_lang"] for r in maps if int(r["Type"]) == 3}
    children = defaultdict(list)
    for row in area_rows:
        children[int(row["ParentAreaID"])].append(row)
    by_id = {int(r["ID"]): r for r in area_rows}
    nodes = {int(r["ID"]): int(r["Flags"]) & 3 for r in taxi_nodes}
    result = {}
    for ui_map, name in sorted(zones.items()):
        rows = [r for r in assignments if int(r["UiMapID"]) == ui_map]
        tops = {int(r["AreaID"]) for r in rows} & by_id.keys()
        levels = {int(a["ExplorationLevel"]) for t in tops for a in [by_id[t], *children[t]]} - {0}
        if not levels:
            continue
        taxi = []
        for node, continent, x, y, title in sorted(flight_masters(taxi_nodes)):
            whole = [r for r in rows if int(r["MapID"]) == continent and int(r["WMODoodadPlacementID"]) == 0]
            where = next((xy for r in whole if (xy := project(r, x, y)) is not None), None)
            if node in added_nodes and nodes[node] and where:
                taxi.append(
                    {
                        "side": nodes[node],
                        "map": ui_map,
                        "x": round(where[0], 4),
                        "y": round(where[1], 4),
                        "name": title,
                    }
                )
        result[ui_map] = {"name": name, "min": min(levels), "max": max(levels), "taxi": taxi}
    return result


def render(zones, areas, new_lands):
    lines = [
        "-- Generated by tools/diff_forever.py — do not edit.",
        f"-- wago.tools DB2 at {BUILD} (Forever) against {ERA} (Classic Era): an ID only Forever has, Forever added.",
        "-- quests: zone map -> the added QuestV2 IDs whose QuestPOIBlob sits on it. A quest with no blob has no zone,",
        "-- so it is left out; the addon compares these with Data.quests at runtime.",
        "-- areas: the added AreaTable IDs.",
        "-- lands: each added zone map with a level range: the least and greatest non-zero ExplorationLevel of its",
        "-- areas; taxi: its flight masters that serve a side (Flags 1 Alliance, 2 Horde), projected onto it.",
        "---@type string, AGFNamespace",
        "local _, ns = ...",
        "-- stylua: ignore",
        "ns.Data.forever = {",
        "\tquests = {",
    ]
    lines.extend(f"\t\t[{ui_map}] = {{ {', '.join(map(str, ids))} }}," for ui_map, ids in zones.items())
    lines.extend(["\t},", "\tareas = {"])
    for start in range(0, len(areas), AREAS_PER_LINE):
        lines.append("\t\t" + " ".join(f"[{area}] = true," for area in areas[start : start + AREAS_PER_LINE]))
    lines.extend(["\t},", "\tlands = {"])
    for ui_map, land in sorted(new_lands.items()):
        lines.append(
            f"\t\t[{ui_map}] = {{ name = {lua(land['name'])}, min = {land['min']}, max = {land['max']}, taxi = {{"
        )
        lines.extend(f"\t\t\t{lua(node)}," for node in land["taxi"])
        lines.append("\t\t} },")
    return "\n".join(lines + ["\t},", "}", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--refresh", action="store_true", help="redownload the pinned sources")
    mode.add_argument("--offline", action="store_true", help="require cached sources")
    options = vars(parser.parse_args())

    def both(name, columns=("ID",)):
        return added(db2(name, columns, **options), db2(name, columns, build=ERA, **options))

    quests = both("QuestV2")
    zones = zone_quests(db2("QuestPOIBlob", ("QuestID", "UiMapID"), **options), quests)
    areas = both("AreaTable")
    ui_maps = db2("UiMap", ("ID", "Name_lang", "Type"), **options)
    era_maps = {int(r["ID"]) for r in db2("UiMap", ("ID",), build=ERA, **options)}
    new_lands = lands(
        [r for r in ui_maps if int(r["ID"]) not in era_maps],
        db2(
            "UiMapAssignment", ("UiMapID", "MapID", "AreaID", "WMODoodadPlacementID", "Region_0", "UiMin_0"), **options
        ),
        db2("AreaTable", ("ID", "ParentAreaID", "ExplorationLevel"), **options),
        db2("TaxiNodes", TAXI_COLUMNS, **options),
        set(both("TaxiNodes")),
    )
    if not quests or not areas:
        raise ValueError("Forever added nothing; leaving existing output untouched")
    print(f"QuestV2: {len(quests)} added, {sum(map(len, zones.values()))} placed on {len(zones)} zone maps")
    print(f"AreaTable: {len(areas)} added")
    for ui_map, land in new_lands.items():
        print(f"Land {ui_map} {land['name']}: {land['min']}-{land['max']}, {len(land['taxi'])} flight masters")
    for name in REPORTED:
        ids = both(name)
        print(f"{name}: {len(ids)} added: {', '.join(map(str, ids))}")
    OUTPUT.write_text(render(zones, areas, new_lands), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({OUTPUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, KeyError, csv.Error, urllib.error.URLError) as error:
        sys.exit(f"diff_forever: {error}")
