#!/usr/bin/env python3
"""Generate Forever's dungeon and raid boss ability ids (Data/Abilities.lua) from CMaNGOS classic-db.

A creature's abilities are the spell ids its EventAI script casts (`creature_ai_scripts` action type 11), its
`creature_template_spells` set and its `creature_spell_list` list. Only creatures that spawn on a map the addon
browses are kept, and only elites and bosses (`Rank` at least 1): trash is not shown, and no other addon's table
is copied. Forever renumbers Classic ids, so each id is kept only while it resolves in wago.tools' SpellName (a
named, non-obsolete spell) and SpellEffect (a real effect). An id that resolves to nothing is dropped, never
shipped. The page resolves the name, icon and tooltip from the client at runtime, so only ids are bundled.

CMaNGOS classic-db is GPL-3.0 and already pinned for the route geometry (docs/dungeon-sources.md); this extends
that use to the abilities those records name.
"""

import gzip
import io
import re
from collections import defaultdict

import gen_quests

ROOT = gen_quests.ROOT
OUTPUT = ROOT / "Data" / "Abilities.lua"
RAIDS = ROOT / "Integrations" / "Raids.lua"
# The tables this generator reads from the pinned classic-db dump.
TABLES = {
    "creature",
    "creature_template",
    "creature_template_spells",
    "creature_spell_list",
    "creature_ai_scripts",
}
# creature_ai_scripts.actionN_type: ACTION_T_CAST.
CAST = 11
SPELL_SLOTS = range(1, 11)
ACTION_SLOTS = range(1, 4)
# A named Classic id Forever kept as an obsolete copy is not a live ability.
OBSOLETE = re.compile(r"\((?:OLD|TEST|NYI)\)|deprecated|unused|zzold", re.IGNORECASE)


def read_tables(lines):
    """The pinned dump's ability tables as row dicts, by column order, never executing SQL."""
    return gen_quests.read_tables(lines, TABLES)


def instance_maps(raids):
    """Every Map.ID the Dungeons tab browses: the generated dungeon ranges and the raid registry's maps."""
    return set(gen_quests.DUNGEON_LEVELS) | {int(m) for m in re.findall(r"\bmap = (\d+)", raids)}


def creature_abilities(tables):
    """Each creature entry's cast ids, before the build gate: EventAI casts, its spell set and its spell list."""
    by_entry, by_list = defaultdict(set), defaultdict(set)
    template = {int(row["Entry"]): row for row in tables["creature_template"]}
    for row in tables["creature_template_spells"]:
        entry = int(row["entry"])
        for slot in SPELL_SLOTS:
            by_entry[entry].add(int(row.get(f"spell{slot}") or 0))
    for row in tables["creature_spell_list"]:
        by_list[int(row["Id"])].add(int(row["SpellId"]))
    for row in tables["creature_ai_scripts"]:
        entry = int(row["creature_id"])
        for slot in ACTION_SLOTS:
            if int(row.get(f"action{slot}_type") or 0) == CAST:
                by_entry[entry].add(int(row.get(f"action{slot}_param1") or 0))
    for entry, row in template.items():
        spell_list = int(row["SpellList"] or 0)
        if spell_list:
            by_entry[entry] |= by_list.get(spell_list, set())
    return {entry: {spell for spell in spells if spell > 0} for entry, spells in by_entry.items()}


def resolves(spell, names, effects):
    """Whether this build names the spell and gives it a real effect: an obsolete or empty name is not a row."""
    name = names.get(spell, "")
    return bool(name) and not OBSOLETE.search(name) and spell in effects


def generate(tables, maps, names, effects):
    """{npcID: [spellID...]} for elite-and-above creatures spawning on a browsed map, each id gated on this build."""
    rank = {int(row["Entry"]): int(row["Rank"] or 0) for row in tables["creature_template"]}
    spawns = defaultdict(set)
    for row in tables["creature"]:
        spawns[int(row["id"])].add(int(row["map"]))
    resolved = {}
    for entry, spells in creature_abilities(tables).items():
        if rank.get(entry, 0) < 1 or not (spawns.get(entry, set()) & maps):
            continue
        # One row per ability name: two ranks of the same spell are one ability in the journal, and the lowest id is
        # the one the creature's own record casts first.
        kept, seen = [], set()
        for spell in sorted(spells):
            if not resolves(spell, names, effects) or names[spell] in seen:
                continue
            seen.add(names[spell])
            kept.append(spell)
        if kept:
            resolved[entry] = kept
    return resolved


def render(resolved):
    commit = gen_quests.CLASSICDB_COMMIT
    lines = [
        "-- Generated by tools/gen_abilities.py: do not edit.",
        f"-- CMaNGOS classic-db (GPL-3.0), pinned: https://raw.githubusercontent.com/cmangos/classic-db/{commit}/Full_DB/ClassicDB_1_12_1_z2815.sql.gz",
        "-- creature_ai_scripts, creature_template_spells and creature_spell_list: each creature that spawns on a",
        "-- browsed instance map, its cast ids kept only while wago.tools names them and gives them an effect at",
        f"-- https://wago.tools/db2/SpellName/csv?build={gen_quests.BUILD}",
        "-- Keyed by creature entry (npcID); the client supplies each ability's name, icon and tooltip.",
        "---@type string, AGFNamespace",
        "local _, ns = ...",
        "ns.Data.bossAbilities = {",
    ]
    for entry in sorted(resolved):
        spells = ", ".join(str(spell) for spell in resolved[entry])
        lines.append(f"\t[{entry}] = {{ {spells} }},")
    return "\n".join([*lines, "}", ""])


def main():
    options = gen_quests.source_options(__doc__)
    content = gen_quests.download(
        gen_quests.CLASSICDB_URL, f"classicdb-{gen_quests.CLASSICDB_COMMIT[:7]}.sql.gz", **options
    )
    with gzip.open(io.BytesIO(content), "rt", encoding="utf-8") as dump:
        tables = read_tables(dump)
    names = {
        int(row["ID"]): row["Name_lang"] or "" for row in gen_quests.db2("SpellName", ("ID", "Name_lang"), **options)
    }
    effects = {
        int(row["SpellID"])
        for row in gen_quests.db2("SpellEffect", ("SpellID", "Effect"), **options)
        if int(row["Effect"] or 0) != 0
    }
    resolved = generate(tables, instance_maps(RAIDS.read_text(encoding="utf-8")), names, effects)
    if not resolved:
        raise ValueError("No ability ids resolved; leaving existing output untouched")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(resolved), encoding="utf-8")
    print(
        f"Wrote {len(resolved)} creature ability sets and {sum(map(len, resolved.values()))} rows: "
        f"{OUTPUT.relative_to(ROOT)} ({OUTPUT.stat().st_size:,} bytes)"
    )


if __name__ == "__main__":
    gen_quests.run(main, "gen_abilities")
