#!/usr/bin/env python3
"""Generate the test-only QuestieDB quest corpus (tests/fixtures/quests.lua and towns.lua; stdlib only).

The corpus is the model fixture: one deterministic world for the headless specs, composed by the addon's own
QuestieSource build over a pinned QuestieDB release, so what the specs plan against is what a player's game carries.
tools/corpus.lua loads the baked store offline in LuaJIT and writes the two files; this downloads and verifies the
release, supplies the client's skill and faction names, and keeps the pin. The classic-db corpus this replaces is
gone; tools/gen_quests.py still generates Forever's shipped route geometry from CMaNGOS.
"""

import hashlib
import io
import os
import subprocess
import sys
import urllib.error
import zipfile
from pathlib import Path

import gen_quests

ROOT = Path(__file__).resolve().parent.parent
CACHE = gen_quests.CACHE
FIXTURE = ROOT / "tests" / "fixtures" / "quests.lua"
TOWN_FIXTURE = ROOT / "tests" / "fixtures" / "towns.lua"
# QuestieDB's Forever release, pinned to the tag and the asset's sha256. The refresh workflow moves the tag.
QUESTIEDB_TAG = "v1.0.4"
QUESTIEDB_SHA256 = "2435d382c1a78c0876064c197196e73b9f417669f75187f51cc311fd8c2c19e1"
QUESTIEDB_URL = f"https://github.com/Questie/QuestieDB/releases/download/{QUESTIEDB_TAG}/QuestieDB-Forever.zip"


def verify(content):
    digest = hashlib.sha256(content).hexdigest()
    if digest != QUESTIEDB_SHA256:
        raise ValueError(f"QuestieDB {QUESTIEDB_TAG}: sha256 {digest} does not match the pin")


def unpack(content):
    """The release's addon directory, extracted once under the shared cache."""
    target = CACHE / f"questiedb-{QUESTIEDB_TAG}"
    if (target / "QuestieDB" / "QuestieDB_Forever.toc").is_file():
        return target / "QuestieDB"
    target.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(io.BytesIO(content)) as archive:
        archive.extractall(target)
    return target / "QuestieDB"


def names_file(options):
    """The English names of every skill line and faction, from the pinned client tables, as tools/corpus.lua's env."""
    skills = {
        int(row["ID"]): row["DisplayName_lang"]
        for row in gen_quests.db2("SkillLine", ("ID", "DisplayName_lang"), **options)
        if row["DisplayName_lang"]
    }
    factions = {
        int(row["ID"]): row["Name_lang"]
        for row in gen_quests.db2("Faction", ("ID", "Name_lang"), **options)
        if row["Name_lang"]
    }
    CACHE.mkdir(parents=True, exist_ok=True)
    path = CACHE / f"questiedb-names-{gen_quests.BUILD}.lua"
    path.write_text(
        "-- Generated by tools/gen_corpus.py: the client's skill and faction names, never shipped.\n"
        "-- stylua: ignore\nreturn {\n"
        f"\tskills = {gen_quests.lua(skills)},\n"
        f"\tfactions = {gen_quests.lua(factions)},\n"
        "}\n",
        encoding="utf-8",
    )
    return path


def main():
    options = gen_quests.source_options(__doc__)
    content = gen_quests.download(QUESTIEDB_URL, f"questiedb-{QUESTIEDB_TAG}.zip", **options)
    try:
        verify(content)
    except ValueError:
        if options.get("offline"):
            raise
        content = gen_quests.download(QUESTIEDB_URL, f"questiedb-{QUESTIEDB_TAG}.zip", refresh=True, offline=False)
        verify(content)
    root = unpack(content)
    environment = os.environ.copy()
    environment.update(
        AGF_QUESTIEDB=str(root),
        AGF_CORPUS_NAMES=str(names_file(options)),
        AGF_QUESTIEDB_TAG=QUESTIEDB_TAG,
        AGF_QUESTIEDB_SHA256=QUESTIEDB_SHA256,
        AGF_CLIENT_BUILD=gen_quests.BUILD,
    )
    subprocess.run(["luajit", "tools/corpus.lua"], cwd=ROOT, check=True, env=environment)
    for path in (FIXTURE, TOWN_FIXTURE):
        if not path.is_file() or not path.stat().st_size:
            raise ValueError(f"tools/corpus.lua wrote no {path.relative_to(ROOT)}")
        print(f"Wrote {path.relative_to(ROOT)} ({path.stat().st_size:,} bytes)")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, KeyError, subprocess.CalledProcessError, urllib.error.URLError) as error:
        sys.exit(f"gen_corpus: {error}")
