#!/usr/bin/env python3
"""Emit Data/ZoneArt.lua: each quest zone's world-map overlays, for the overview's round zone icons (stdlib only).

The client gives a zone's base tiles by C_Map.GetMapArtLayerTextures, but its overlays (the towns, forests and water)
only once explored (C_MapExplorationInfo), so an icon of a zone not yet seen would be bare parchment. This reads them
from the pinned build's DB2 on wago.tools, cached in tools/.cache like gen_quests.py's sources: every WorldMapOverlay
with a texture and no player condition on the zone's art (UiMapXMapArt, phase 0), its tiles (WorldMapOverlayTile,
layer 0) in row-major order. Only the zones Data/Quests.lua has, and only those whose art is the 1002x668 canvas of
256-pixel tiles the addon lays out (docs/design.md §2.2).
"""

import argparse
import csv
import re
import sys
import urllib.error
from collections import defaultdict

from gen_quests import BUILD, ROOT, db2

OUTPUT = ROOT / "Data" / "ZoneArt.lua"
QUESTS = ROOT / "Data" / "Quests.lua"
CANVAS, TILE = (1002, 668), 256


def quest_zones(text):
    """The uiMap IDs of Data/Quests.lua's `zones` table."""
    block = re.search(r"^\tzones = \{\n(.*?)^\t\},", text, re.MULTILINE | re.DOTALL)
    if not block:
        raise ValueError("Data/Quests.lua has no zones table")
    return sorted(int(ui_map) for ui_map in re.findall(r"^\t\t\[(\d+)\] = ", block[1], re.MULTILINE))


def tiles_needed(width, height):
    """How many tiles an overlay of this size has, row-major, as MapExplorationPinMixin lays them out."""
    return -(-width // TILE) * -(-height // TILE)


def zone_art(zones, map_art, arts, layers, overlay_rows, tile_rows):
    """Each zone -> its overlays as (offsetX, offsetY, width, height, tiles), by overlay ID."""
    art_of = {}
    for row in sorted(map_art, key=lambda r: int(r["ID"])):
        ui_map = int(row["UiMapID"])
        if ui_map in zones and int(row["PhaseID"]) == 0 and ui_map not in art_of:
            art_of[ui_map] = int(row["UiMapArtID"])
    style = {int(r["ID"]): int(r["UiMapArtStyleID"]) for r in arts}
    canvas = {
        int(r["UiMapArtStyleID"]): (int(r["LayerWidth"]), int(r["LayerHeight"]), int(r["TileWidth"]))
        for r in layers
        if int(r["LayerIndex"]) == 0
    }
    tiles = defaultdict(list)
    for row in tile_rows:
        if int(row["LayerIndex"]) == 0:
            tiles[int(row["WorldMapOverlayID"])].append(row)
    by_art = defaultdict(list)
    for row in sorted(overlay_rows, key=lambda r: int(r["ID"])):
        width, height = int(row["TextureWidth"]), int(row["TextureHeight"])
        if not (width and height) or int(row["PlayerConditionID"]):
            continue
        ordered = sorted(tiles[int(row["ID"])], key=lambda t: (int(t["RowIndex"]), int(t["ColIndex"])))
        files = [int(t["FileDataID"]) for t in ordered]
        if len(files) != tiles_needed(width, height) or not all(files):
            continue
        by_art[int(row["UiMapArtID"])].append((int(row["OffsetX"]), int(row["OffsetY"]), width, height, files))
    result = {}
    for ui_map in zones:
        art = art_of.get(ui_map)
        if art is None or canvas.get(style.get(art)) != (*CANVAS, TILE) or not by_art[art]:
            continue
        result[ui_map] = by_art[art]
    return result


def render(art):
    lines = [
        "-- Generated by tools/gen_zoneart.py — do not edit.",
        f"-- wago.tools UiMapXMapArt, UiMapArt, UiMapArtStyleLayer, WorldMapOverlay, WorldMapOverlayTile at {BUILD}.",
        "-- Each quest zone's world-map overlays, every one explored or not: { offsetX, offsetY, width, height, tile",
        "-- FileDataIDs row-major } on the zone's 1002x668 art, 256-pixel tiles, by overlay ID (docs/design.md §2.2).",
        "---@type string, AGFNamespace",
        "local _, ns = ...",
        "-- stylua: ignore",
        "ns.Data.zoneArt = {",
    ]
    for ui_map, overlays in art.items():
        lines.append(f"\t[{ui_map}] = {{")
        lines.extend(f"\t\t{{ {', '.join(map(str, (ox, oy, w, h, *files)))} }}," for ox, oy, w, h, files in overlays)
        lines.append("\t},")
    return "\n".join([*lines, "}", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--refresh", action="store_true", help="redownload the pinned sources")
    mode.add_argument("--offline", action="store_true", help="require cached sources")
    options = vars(parser.parse_args())
    zones = quest_zones(QUESTS.read_text(encoding="utf-8"))
    art = zone_art(
        set(zones),
        db2("UiMapXMapArt", ("ID", "UiMapID", "UiMapArtID", "PhaseID"), **options),
        db2("UiMapArt", ("ID", "UiMapArtStyleID"), **options),
        db2(
            "UiMapArtStyleLayer", ("UiMapArtStyleID", "LayerIndex", "LayerWidth", "LayerHeight", "TileWidth"), **options
        ),
        db2(
            "WorldMapOverlay",
            ("ID", "UiMapArtID", "TextureWidth", "TextureHeight", "OffsetX", "OffsetY", "PlayerConditionID"),
            **options,
        ),
        db2(
            "WorldMapOverlayTile", ("WorldMapOverlayID", "RowIndex", "ColIndex", "LayerIndex", "FileDataID"), **options
        ),
    )
    if not art:
        raise ValueError("no zone art; leaving existing output untouched")
    OUTPUT.write_text(render(art), encoding="utf-8")
    overlays = sum(len(each) for each in art.values())
    print(f"{len(art)} of {len(zones)} zones, {overlays} overlays")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({OUTPUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, KeyError, csv.Error, urllib.error.URLError) as error:
        sys.exit(f"gen_zoneart: {error}")
