"""Generate a Classic encounter fallback from the quest baseline's pinned database."""

import argparse
import gzip
import io
import sys
from pathlib import Path

from gen_quests import CLASSICDB_COMMIT, CLASSICDB_URL, DUNGEON_LEVELS, download, lua, read_tables

TABLES = {"instance_dungeon_encounters", "instance_encounters", "creature_template"}
OUTPUT = Path(__file__).resolve().parent.parent / "Data" / "DungeonBosses.lua"


def encounters(tables):
    credits = {row["entry"]: row for row in tables["instance_encounters"]}
    creatures = {row["Entry"]: row for row in tables["creature_template"]}
    result = {}
    for row in sorted(tables["instance_dungeon_encounters"], key=lambda r: (r["EncounterIndex"], r["Id"])):
        instance = row["MapId"]
        if instance not in DUNGEON_LEVELS or row["Difficulty"] != 0:
            continue
        credit = credits.get(row["Id"])
        npc = creatures.get(credit["creditEntry"]) if credit and credit["creditType"] == 0 else None
        if not npc:
            continue
        bosses = result.setdefault(instance, [])
        if any(boss["id"] == npc["Entry"] for boss in bosses):
            continue
        bosses.append(
            {
                "id": npc["Entry"],
                "name": row["EncounterName"],
                "rank": 3,
                "low": npc["MinLevel"],
                "high": npc["MaxLevel"],
            }
        )
    missing = DUNGEON_LEVELS.keys() - result.keys()
    if missing:
        raise ValueError(f"No verified encounters for Classic instances: {sorted(missing)}")
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--offline", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = download(CLASSICDB_URL, f"classicdb-{CLASSICDB_COMMIT[:7]}.sql.gz", offline=args.offline)
    with gzip.open(io.BytesIO(data), "rt") as stream:
        bosses = encounters(read_tables(stream, TABLES))
    lines = [
        "-- Generated by tools/gen_bosses.py; do not edit.",
        f"-- CMaNGOS classic-db (GPL-3.0), commit {CLASSICDB_COMMIT}",
        "-- https://github.com/cmangos/classic-db (source URL in tools/gen_quests.py)",
        "-- Normal encounters with explicit creature-kill credits; not a complete list of rare spawns.",
        "---@type string, AGFNamespace",
        "local _, ns = ...",
        "-- stylua: ignore",
        "ns.DungeonBosses = {",
    ]
    for instance, rows in sorted(bosses.items()):
        lines.append(f"\t[{instance}] = {{")
        lines.extend(f"\t\t{lua(row)}," for row in rows)
        lines.append("\t},")
    content = "\n".join([*lines, "}", ""])
    if args.check:
        if OUTPUT.read_text() != content:
            sys.exit("Dungeon boss data is stale; run python3 tools/gen_bosses.py")
    else:
        OUTPUT.write_text(content)
    print(f"Verified {sum(map(len, bosses.values()))} encounters in {len(bosses)} dungeons")


if __name__ == "__main__":
    main()
