"""Check the committed QuestieDB corpus: python3 -m unittest discover -s tools -p '*_test.py'."""

import re
import unittest

from gen_corpus import FIXTURE, TOWN_FIXTURE


def span(text, key):
    """The braces' contents of `key = { ... }` in one line, by brace balance."""
    at = text.find(key + " = ")
    if at < 0:
        return None
    opening = text.index("{", at)
    depth = 0
    for index in range(opening, len(text)):
        if text[index] == "{":
            depth += 1
        elif text[index] == "}":
            depth -= 1
            if depth == 0:
                return text[opening + 1 : index]
    raise AssertionError(text)


def slots(body):
    """The slot keys of a `need` table: explicit `[slot] = count`, or positional entries."""
    found, position = set(), 0
    for part in body.split(", "):
        part = part.strip()
        explicit = re.fullmatch(r"\[(\d+)\] = -?\d+", part)
        if explicit:
            found.add(int(explicit[1]))
        elif part not in ("nil", ""):
            position += 1
            found.add(position)
    return found


class CorpusTest(unittest.TestCase):
    """tests/fixtures/quests.lua and towns.lua, generated by tools/gen_corpus.py."""

    TEXT = FIXTURE.read_text(encoding="utf-8")

    def test_areas_are_on_a_map_and_the_quests_objectives(self):
        quests = re.findall(r"^\t\t\[\d+\] = \{.*$", self.TEXT, re.M)
        self.assertGreater(len(quests), 3000)
        count = 0
        for line in quests:
            need, obj = span(line, "need"), span(line, "obj")
            self.assertTrue(bool(need) or obj is None, line)
            self.assertFalse(need and "dungeon = " in line, line)
            if obj is None:
                continue
            known = slots(need)
            for spot in re.findall(r"\{ ([^}]+) \}", obj):
                slot, x, y, r, *ui_map = (int(value) for value in spot.split(", "))
                count += 1
                self.assertIn(slot, known, line)
                self.assertTrue(0 <= x <= 1000 and 0 <= y <= 1000 and r >= 0 and len(ui_map) <= 1, line)
        self.assertGreater(count, 2500)

    def test_the_corpus_names_the_release_and_no_provider_marker(self):
        self.assertIn("QuestieDB Forever, pinned:", self.TEXT)
        self.assertNotIn("provider = true", self.TEXT)

    def test_the_towns_carry_the_gate_names(self):
        towns = TOWN_FIXTURE.read_text(encoding="utf-8")
        for key in ("hubs", "npcs", "skills", "factions"):
            self.assertIn(f"\t{key} = {{", towns)
        self.assertGreater(len(re.findall(r"^\t\t\[\d+\] = \{ name = ", towns, re.M)), 0)


if __name__ == "__main__":
    unittest.main()
